version: '3'
services:

  multicompiler_builder:
    build:
      context: .
      dockerfile: mc_builder_dockerfile
    image: mc_builder:${VNCPORT}
    volumes:
      - "${S2EDIR}/docker/multicompiler-automation:/src"
      - "~/.bashrc:${HOME}/.bashrc:ro"
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - multicompiler_artifacts:/multicompiler
    environment:
      - "S2EDIR=${S2EDIR}"
      - "TERM=${TERM}"
    command: bash -ilc "while :; do sleep 1000000; done"

  binrec:
    build:
      context: .
      dockerfile: Dockerfile
    image: binrec:${VNCPORT}
    volumes:
      - "${S2EDIR}:${S2EDIR}"
      - "~/.bashrc:${HOME}/.bashrc:ro"
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - multicompiler_artifacts:${S2EDIR}/multicompiler
    environment:
      - "S2EDIR=${S2EDIR}"
      - "TERM=${TERM}"
      - CPLUS_INCLUDE_PATH=/usr/include:/usr/include/x86_64-linux-gnu:/usr/include/x86_64-linux-gnu/c++/4.8
      - C_INCLUDE_PATH=/usr/include:/usr/include/x86_64-linux-gnu
    ports:
      - "${VNCPORT}:5900"
    working_dir: "${S2EDIR}"
    command: bash -ilc "while :; do sleep 1000000; done"
    privileged: true
    
  #binrec_i386:
    #build:
      #context: .
      #dockerfile: Dockerfile_i386
    #image: binrec_i386:${VNCPORT}
    #volumes:
      #- "${S2EDIR}:${S2EDIR}"
      #- "~/.bashrc:${HOME}/.bashrc:ro"
      #- /etc/passwd:/etc/passwd:ro
      #- /etc/shadow:/etc/shadow:ro
      #- /etc/group:/etc/group:ro
    #environment:
      #- "S2EDIR=${S2EDIR}"
      #- "TERM=${TERM}"
      #- CPLUS_INCLUDE_PATH=/usr/include:/usr/include/i386-linux-gnu:/usr/include/i386-linux-gnu/c++/4.8
      #- C_INCLUDE_PATH=/usr/include:/usr/include/i386-linux-gnu
    #working_dir: "${S2EDIR}"
    #command: bash -ilc "while :; do sleep 1000000; done"
    #privileged: true

volumes:
  multicompiler_artifacts:
