name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: 'Install tools'
        run: |
          # Python virtual env management
          pipx install pipenv
          # just command runner https://github.com/casey/just#pre-built-binaries
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to "${HOME}/.local/bin"
          # nvm for spelling and markdown linting
          ./get_nvm.sh
          sudo apt update


      - name: 'Init Python'
        run: |
          pipenv sync --dev

      - name: 'Init LLVM 14'
        run: |
          curl -sSL https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz -o - | tar -xJ
          cp clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang-format "${HOME}/.local/bin"

      - name: 'Lint'
        run: |
          just _lint-python
          just _lint-clang
          just _lint-md
          just _lint-rst

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pipenv'

      - name: 'Install tools'
        run: |
          # Python virtual env management
          pipx install pipenv
          # just command runner https://github.com/casey/just#pre-built-binaries
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to "${HOME}/.local/bin"

      - name: 'Init Python'
        run: |
          pipenv sync --dev

      - name: 'Unit Tests'
        run: |
          just _ci-unit-tests

  pip-audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: 'Generate requirements.txt'
        run: |
          pipx run pipfile-requirements Pipfile.lock > requirements.txt

      - uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          inputs: requirements.txt
